spring:
  datasource:
    url: jdbc:mysql://localhost:3306/admin_xc?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update  # 自动更新数据库表结构
      dialect: org.hibernate.dialect.MySQL8Dialect  # 指定 MySQL 方言
    show-sql: true  # 打印 SQL 语句
    properties:
      hibernate:
        format_sql: true
  servlet:
    context-path: /api  # API 路径前缀
